name: .NET

on:
  release:
    types:
      published

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Archive Release
      run: |
        touch release.tar.gz
        tar -czvf release.tar.gz --exclude='./*.tar.gz'        
        
            
